language: node_js
node_js:
- '5.0'
sudo: false
after_script: npm install codecov.io && cat ./coverage/lcov.info | codecov
deploy:
  - provider: npm
    email: tituswormer@gmail.com
    api_key:
        secure: Uwvuinw4bpjhUUvxCoJpBhwMnbLBIM+0IvRkywVmlBK00jhnQEU+wCi51ujq2rUJ2oBe6HBMsJjpiO2jnkke4+ovnVzFAli4pF02jlhNKbxvjCgL7opCnY3P0K1ianCbij6MKzL8cXZPq8Y1UWIEZIJcXrH+6Ki2t7IfXpbCUfc=
    on:
      node: '5.0'
      tags: true
  - provider: releases
    api_key:
        secure: Pjl0kiAPE3E6qA1EYFrGj9oKUehJpANttmVTcZAUT8s0M24Nxro9uwVErVpPTCeQZc5XUvXr47hU4w3HDFbICW4QJ++TKuXtMvgW7Cy7aLSYzltm5Ukl8M/8CqATSU66mo58/Q0kWrNNH/zr+a4CvWTYuiYOxtVsBXUfIiksd68=
    file:
      - "cuss.js"
      - "cuss.min.js"
    on:
      tags: true
